layout_spectrum: 0.2170213
typography_spectrum: 0.7638298
color:
  saturation: 0.5106383
  brandStrength: 0.4404255
  lightness: 0.6191489
  brandColors:
    - '#000000'
    - '#0043CE'
    - '#DEE5F8'
    - '#9397A5'
    - '#11ADFE'
  rhythmicContrast: 0.2255319
name: Protecomp
