layout_spectrum: 0.2170213
color:
  saturation: 0.3723404
  brandStrength: 0.6161952
  lightness: 0.706383
  rhythmicContrast: 0.2255319
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
typography_spectrum: 0.7638298
name: Protecomp
